### ISSUE TITLE
Alternate names or prefixes for `get`, `put`, and so on

### ISSUE THREAD

**Issue by i-am-the-slime** [cb372/scalacache#109]
I already have `get` in scope as a function for getting the value in a state monad (and the inverse for `put`). Is there any way that I can have different names for these functions? Can I just rename the imports? Something like `import scalacache.{put => cache, get => lookup}`?

**Comment by cb372** [comment]
Yes, renaming the imports like that is totally fine. But you probably want to keep the wildcard import, as this brings some codecs and other goodies into implicit scope. So I would go for something like

```scala
import scalacache.{put => cache, get => lookup, _}
import scalacache.caffeine._ // or whatever implementation you're using
```
