### ISSUE TITLE
Need to specify @cacheKeyExclude to flags

### ISSUE THREAD

**Issue by k4200** [cb372/scalacache#121]
Hi,

(Sorry for many posts today.) I found a confusing behavior related to `Flags` that should be documented.

Suppose we have the following class.

```scala
def getUser(id: int)(implicit flags: Flags): User = memoizeSync {
 // ...
}
```

The problem is that the generated key for this method contains `flags` part like this:
```
foopackage.BarClass.getUser(1)(Flags(true,true))
```

So, actually, we need to specify `@cacheKeyExclude` to `flags` like the following:

```scala
def getUser(id: int)(implicit @cacheKeyExclude flags: Flags): User = memoizeSync {
 // ...
}
```

Thank you.

**Comment by cb372** [comment]
Good point, I'd never thought about that.

I guess we can update the macro to make a special case for `Flags` and automatically exclude it from the list of parameters used to generate the key. It's not a very elegant solution, but it's better than the current confusing behaviour.

Do you have any better ideas for fixing this?

**Comment by k4200** [comment]
> I guess we can update the macro to make a special case for Flags and automatically exclude it from the list of parameters used to generate the key.

I have almost zero knowledge about macros, so it's hard for me to come up with better ideas. Having said that, if above is easy to implement, it's not that bad, I believe (although it's not very elegant either as you said).

If it's going to be complicated to implement it, maybe adding a note to the documentation would be enough (at least for me).

**Comment by cb372** [comment]
I wonder if it would make sense to always exclude the implicit parameter block from the generated key?

**Comment by cb372** [comment]
In the end I decided that just improving the documentation is probably good enough.
