### ISSUE TITLE
getAll --- supported by some backends

### ISSUE THREAD

**Issue by fommil** [cb372/scalacache#130]
rather than iterating over everything (which could be slow), some backends may natively support this.

**Comment by cb372** [comment]
Yes, some backends do support it, but not all. This has come up before and I decided against implementing it, for that reason. But I suppose the signature could be something like

```scala
def getAll(): Option[Seq[String]]
```

or

```scala
case object NotSupported
def getAll(): Either[NotSupported.type, Seq[String]]
```

WDYT?

**Comment by fommil** [comment]
How about a HKT fallback :wink:  I gift you this Apache 2.0:

```
  def putAll(
      entries: NonEmptyList[(K, V)]
    )(implicit A: Applicative[M]
    ): M[Unit] =
    entries.traverse {
      case (key, value) => put(key, value)
    }.void

  def getAll(
      keys: NonEmptyList[K]
    )(implicit A: Applicative[M]
    ): M[List[(K, V)]] =
    keys
      .traverse { key =>
        get(key).map(key -> _)
      }
      .map { nel =>
        nel.toList.collect { case (key, Some(value)) => key -> value }
      }
```

This type signature doesn't allow for "partial success" in the sense that if the containing monad says there was a problem, it all fails. Not sure if that's something you want to care about. (btw, by "partial success" I mean things like I/O errors, not failing to find the cached value)
