### ISSUE TITLE
configuration parameter to disable logging of cache even when logger is enabled.

### ISSUE THREAD

**Issue by pramodrangaraju** [cb372/scalacache#132]
All specific implementations of cache extend LoggingSupport and hence help log in debug mode. (/core/shared/src/main/scala/scalacache/LoggingSupport.scala -line 22). 
The specific hit/miss logs are suppressing the actual logs and hence there is a need for specific configuration parameter to subside these logs.

**Comment by cb372** [comment]
Sorry, I don't quite understand your issue. If you want to enable DEBUG level logging for your application but disable ScalaCache's DEBUG logging, it would make more sense to do that using your application's logging configuration.

e.g. if you are using Logback for logging, add something like this to your `logback.xml`:

```
<logger name="scalacache" level="INFO" />
```
