### ISSUE TITLE
Proper Scala.js support

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#147]
* Provide a cache backend that works with Scala.js
* Remove any dependencies from core that break Scala.js
* Make sure scala.js tests are being run as part of the build (right now `coreJS/test` doesn't seem to do anything)

I'm hopelessly ignorant about Scala.js so... help wanted!

**Comment by aappddeevv** [comment]
Related: #133

**Comment by cb372** [comment]
I'm slightly less ignorant about Scala.js these days. See #214

**Comment by lewisjkl** [comment]
Closing. See #354.
