### ISSUE TITLE
Microsite

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#148]
Use sbt-microsites to make a website.

The readme is now checked with `tut` so it shouldn't be too much effort to port it over.

Ideally the site would split the documentation into sensible categories, so it's easier to read through than the giant README we currently have.

**Comment by jan0sch** [comment]
Would it be okay for you if the generated big README stuff is killed in the process or do you want to keep that one?

**Comment by cb372** [comment]
Thank you for working on this! The README can become a very short doc containing just a link to the microsite.
