### ISSUE TITLE
Incompatible version of cats between scalacache-monix and scalacache-circe

### ISSUE THREAD

**Issue by david93111** [cb372/scalacache#154]
Actually scalacache-monix uses monix 3.0.0-M1 with cats 1.0.0-MF, scalacache-circe uses circe 0.8.0 that uses internally cats 0.9.0, both version are incompatible, there's a new version of circe 0.9.0-M1 that uses cats 1.0.0-MF (also there is 0.9.0-M2 that uses cats 1.0.0-RC1) but some methods may have disappear, so, some changes are going to bee needed on scalacache-circe (i tried to use circe 0.9.0-M1 it and NoSuchMethodError appears with io.circe.JsonObject$.fromMapAndVector ). Also there is a version for monix, 2.3.2 that also uses cat 0.9.0, so both options can be tried to achieve compatibility over the same library (is weird trying to use capabilities of scalache that conflicts each others)

Maybe this issue is also on your radar and you know about it you can tell me, also if i can help with a solution you can contact me also.

By the way, a great library, i see a lot of potential on it, so keep the great work!

**Comment by cb372** [comment]
Wow, what a mess. Thank you for the detailed report.

To be honest I was just waiting for Cats 1.0 to hurry up and get released, which will sort out all of these problems. I'll see if I can come up with an interim solution.

**Comment by cb372** [comment]
I've just released 0.22.0, which upgrades both circe and monix. So everything now transitively depends on cats 1.0.1.
