### ISSUE TITLE
Memoization and cache key: how is it based on class name?

### ISSUE THREAD

**Issue by bbarker** [cb372/scalacache#166]
On the memoize [doc page](http://cb372.github.io/scalacache/docs/memoization.html#cache-key-generation) it states that the class's name is included. 

However, when I tried out memoize (or memoizeSync in my specific case), I didn't observe the behavior: it seemed that each subclass that uses the memoized method tramples the results for other subclasses, i.e., the first subclass that is initialized wins.

If instead I use `cacheing` like this (using `getClass.getName`) it seems to work as expected, retrieving the most specific class name and adding it to the key:

```scala
  def initializeGraph(cowIdMaybe: Option[Int]): DynamicGraph =
    sync.caching(getClass.getName, sim, cowIdMaybe)(ttl = None) {
      initializeGraphInternal(cowIdMaybe)
    }

  protected def initializeGraphInternal(cowIdMaybe: Option[Int]): DynamicGraph = {
    // ... much code, much compute
  }
```

**Comment by cb372** [comment]
I re-read your issue and noticed that you were talking about subclasses, so I think this is probably what you are experiencing:

```scala
package example

import scalacache._
import scalacache.memoization._
import scalacache.modes.sync._
import scalacache.caffeine._
import com.github.benmanes.caffeine.cache.Caffeine

object Hello extends App {

  val underlyingCaffeineCache = Caffeine.newBuilder().build[String, Entry[String]]

  implicit val cache: Cache[String] = CaffeineCache(underlyingCaffeineCache)

  val foo = new Foo
  val bar = new Bar

  println(foo.yo(123, "hello"))
  // prints "wow from Foo"

  println(bar.yo(123, "hello"))
  // prints "wow from Foo"

  println(underlyingCaffeineCache.asMap.keySet)
  // prints "[example.Parent.yo(123, hello)]"

}

abstract class Parent(implicit cache: Cache[String]) {

  def wow: String

  def yo(a: Int, b: String): String = memoizeSync(None) {
    wow
  }

}
class Foo(implicit cache: Cache[String]) extends Parent {
  def wow = "wow from Foo"
}

class Bar(implicit cache: Cache[String]) extends Parent {
  def wow = "wow from Foo"
}
```

Unfortunately because of the way memoization is implemented using a macro, the class name used in the key will be the name of the class where the method is defined, i.e. `Parent` in this case.

I think the workaround you found using `getClass.getName` is probably the best way to do what you want. Just a shame that you miss out on the automatic key generation magic.

**Comment by bbarker** [comment]
> Unfortunately because of the way memoization is implemented using a macro, the class name used in the key will be the name of the class where the method is defined, i.e. Parent in this case.

I suspected this might be the case, but never having written or looked much at macro code, I wasn't sure offhand.

> I think the workaround you found using getClass.getName is probably the best way to do what you want. Just a shame that you miss out on the automatic key generation magic.

Good to know, thanks for looking into this. It isn't such a bad workaround really, and I probably need to specify custom keys anyway from time to time.

**Comment by cb372** [comment]
Ah, yes it should be "wow from Bar". Sorry for the typo.
