### ISSUE TITLE
0.24.2 is published to maven but not mentioned on the github releases page

### ISSUE THREAD

**Issue by mjsmith707** [cb372/scalacache#192]
Is this a legitimate release or not?
https://mvnrepository.com/artifact/com.github.cb372/scalacache-core_2.11/0.24.2

I do not see it here: 
https://github.com/cb372/scalacache/releases

I would love to use it since it makes the underlying cache publicly accessible now (I've just been using reflection previously). Thanks.

**Comment by cb372** [comment]
That's odd. Not sure what happened to the tag.

Yes, it's a legitimate release.

I'll also try and make a new release this week anyway.

**Comment by cb372** [comment]
0.24.2 has now magically appeared on the releases page!
