### ISSUE TITLE
scalacache-ehcache plugin not in maven central repository

### ISSUE THREAD

**Issue by FunkyYang** [cb372/scalacache#198]
:(

**Comment by cb372** [comment]
Yes it is. The latest version is here: https://search.maven.org/artifact/com.github.cb372/scalacache-ehcache_2.12/0.24.3/jar

Don't forget that for Scala libraries, the Scala binary version is included as a suffix on the module name, so it's listed on Maven Central as `scalacache-ehcache_2.12` (for Scala 2.12.x), `scalacache-ehcache_2.11` (for Scala 2.11.x), etc.
