### ISSUE TITLE
Ambigous implicit for cats IO

### ISSUE THREAD

**Issue by Katrix** [cb372/scalacache#228]
When I have `import scalacache.CatsEffect.modes._` in my code, I get an ambigous implicit.

```
[error]  both value io in object modes of type => scalacache.Mode[cats.effect.IO]
[error]  and method async in object modes of type [F[_]](implicit F: cats.effect.Async[F])scalacache.Mode[F]
[error]  match expected type scalacache.Mode[cats.effect.IO]
```

**Comment by cb372** [comment]
I'm surprised you got an ambiguous implicit, as the `IO` one is more specific than the `async` one.

Anyway, we should remove the `io` one. I left it there for backwards compatibility but it seems to be causing trouble for a few people.

In the meantime, changing your import to `import scalacache.CatsEffect.modes.async` should work.
