### ISSUE TITLE
Update jedis to 2.10.2 - fixes connection leak issue in JedisPool

### ISSUE THREAD

**Issue by jruusu** [cb372/scalacache#243]
Update jedis to 2.10.2 in order to fix https://github.com/xetorthio/jedis/issues/1920 - a connection leak leading to _JedisPool exhausted_ exceptions in Jedis 2.10.0

See Pull Request by scala-steward: #236 

We have been running jedis 2.10.2 in production, and confirmed the upgrade fixes the connection leak issue observed on jedis 2.10.0.

Thank you!

**Comment by cb372** [comment]
Thanks for the report. Merged!
