### ISSUE TITLE
Publish for Scala 2.13

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#254]
Started work on this a while ago in #190. These days all the necessary dependencies should already be cross-published for 2.13.0-RC1 I think.

**Comment by morozov1** [comment]
Is there any progress?

**Comment by cb372** [comment]
Sorry, I forgot to close this. v0.28.0 has already been published for Scala 2.13.0.

**Comment by yuriy-yarosh** [comment]
@cb372 
Hi, Chris, could you please also publish scalacache-cats-effect for 1.0.0-M1 ?

**Comment by lewisjkl** [comment]
Hey @yuriy-yarosh,

Scalacache 1.0.0-M1 is a little different in that it now includes cats-effect as a core dependency. The idea of "modes" has gone away in favor of supporting cats-effect directly in the core. So if you were depending on scalacache-cats-effect in the past, you now would just need the core module.

**Comment by yuriy-yarosh** [comment]
Thanks @lewisjkl, had figured this one out already.
Hopefully docs will be updated accordingly when 1.0.0 will be ready.
Have a great time of the day.
