### ISSUE TITLE
Support a mode for Slick's DBIO

### ISSUE THREAD

**Issue by jcazevedo** [cb372/scalacache#292]
I'm currently using ScalaCache over Slick's `DBIO` using [`kubukoz/slick-effect`](https://github.com/kubukoz/slick-effect) with `scalacache-cats-effect`, whose mode provides an implicit conversion of Cats' `Async` instances to ScalaCache's `Async`. This works, but adds a possibly unnecessary dependency on [`typelevel/cats-effect`](https://github.com/typelevel/cats-effect). Is having a mode for Slick's `DBIO` something suitable for a ScalaCache module? I can work on a pull request providing it if it's something suitable for the library.

**Comment by cb372** [comment]
Hi! This does sound useful, but recently I've been trying to reduce the number of dependencies on other Scala libraries, as every dependency increases maintenance overhead, especially when new versions of Scala come along.

If you'd like to release this as a separate library I'd happily link to it from the ScalaCache documentation.

Maybe the time has come to move ScalaCache to its own organisation, where things like `scalacache-slick` could also live.

**Comment by tnielens** [comment]
scalacache 1.0 should be compatible with cats-effect 3. Support won't be needed in scalacache as there are CE3 abstractions implementations in https://github.com/kubukoz/slick-effect .

**Comment by kubukoz** [comment]
Modes are now gone from main, you can use DBIO with `slick-effect` on the caches that require up to `Sync` (e.g. Memcached won't work as it requires `Async`).
