### ISSUE TITLE
Investigate writing a Play plugin

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#34]

**Comment by cb372** [comment]
and/or a Module, as Play 2.4 will be out soon

**Comment by gmethvin** [comment]
Here's an example of how to create a play module for scalacache: https://github.com/gmethvin/play-scalacache-module.

This binds a `CacheApi` and adds the module so it will be picked up by Play's runtime DI (see https://github.com/gmethvin/play-scalacache-module/blob/master/conf/reference.conf). This means Play (and any other Play modules) will use scalacache to do its caching.

You need to bind a `ScalaCache` instance in another module as well. A user could do this programmatically, which I think is fine for most people.

You could also provide individual modules e.g. `play-scalacache-caffeine` for each cache implementation so you could have things "just work" by default based on configuration.

**Comment by cb372** [comment]
@gmethvin Awesome, thanks!

This comment in the source was interesting:

>It seems like ScalaCache requires the durations to be finite

There's no reason why ScalaCache should add this restriction. I suggest we fix ScalaCache to check for `Duration.Inf` and take it to mean "no TTL". I'll add an issue for it.

**Comment by gmethvin** [comment]
@cb372 Yes, it should be fine to accept just a `Duration` instead of `Option[Duration]` and assume `Duration.Inf` means no timeout.
