### ISSUE TITLE
Support custom serialization

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#35]
Currently hardcoded to use Java serialization for both Redis and Memcached. Might be nice to give people some options, e.g. JSON, Mgspack

**Comment by ymeymann** [comment]
I managed to use JSON (specifically json4s jackson) with Redis by overriding serialize and deserialize methods on the cache. We store only one type of objects in the cache (let's call it Foo), which is a case class. The code is roughly:

```scala
val redisCache = new RedisCache(new JedisPool(host, port)) {
    override def serialize(value: Any): Array[Byte] = {
      val b = new ByteArrayOutputStream()
      serialization.write[Foo](value.asInstanceOf[Foo], b)
      b.toByteArray
    }
    override def deserialize[A](bytes: Array[Byte]): A = {
      val res = serialization.read[Foo](new String(bytes, "UTF8"))
      res.asInstanceOf[A]
    }
}
```

**Comment by lloydmeta** [comment]
I think something along the lines of what Shade does with having a[ `Codec` typeclass](https://github.com/alexandru/shade/blob/master/src/main/scala/shade/memcached/Codec.scala) for `put` and `get` operations might make sense. For in-memory caches (like Guava), we can just ignore that parameter.

To make things convenient, we can have default primitive type class instances and provide an auto Java-serialisation-based one via another import. People who wish to use their own JSON or Msgpack serialisation can simply provide a single conversion to `Codec`. e.g. if using Play JSON

```scala
implicit def toScalacacheCodec(implicit javaFormat: Format[A]): Codec[A] = new Codec[A] {
  def serialize(o: A): Array[Bytes] = {
    val json = o.toJson
    json.toString.getBytes("UTF-8")
  }
  def deserialize(data: Array[Bytes]): A = {
    val json = Json.parse(new String(data, "UTF-8"))
    json.as[A]
  }
}
```

**Comment by joprice** [comment]
:+1: I've had to give up using this for remote caching for this reason.

**Comment by cb372** [comment]
@joprice You'll be happy to hear that ScalaCache 0.8.0 adds support for custom serialization.

Closing this issue.

**Comment by joprice** [comment]
And on my birthday! Thank you!

**Comment by ymeymann** [comment]
Thanks @cb372 & @lloydmeta, and happy birthday @joprice! Just upgraded to 0.8.0, and it is working.

**Comment by lloydmeta** [comment]
Whoa. Happy birthday @joprice :)
