### ISSUE TITLE
Decide what to do about Scala.js support

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#354]
Currently scalacache has pretty half-hearted support for Scala.js. Only the core module is cross-built; we don't provide any integrations for caches that work with Scala.js.

I think the options are:

1. Remove Scala.js support, as it's not providing any value and it increases maintenance overhead
2. Add a cats-effect `Ref`-based cache implementation that we can cross build for Scala.js. We could also cross-build more modules, e.g. the Circe integration.
3. Remove Scala.js for now, then add it back later if/when we have a cache implementation

**Comment by lewisjkl** [comment]
I think the safest option to take here is number 3. We could make a cache implementation for Scala.js up front, but it may make more sense to wait for there to be more demand for such a thing. I’d hate to take on the extra maintenance burden if it ended up being something that people didn’t actually use.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cb372** [comment]
Agreed.

**Comment by kubukoz** [comment]
JS has been dropped from main a while ago. Closing.
