### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#371]
Poor old Travis CI is breaking a lot recently. It hasn't been reporting its results to GitHub properly for days.

**Comment by kubukoz** [comment]
If anyone beats me to it, I'll be more than happy to give some guidance (I have a working setup for sbt-github-actions + sbt-ci-release in https://github.com/kubukoz/caliban-gitlab, will gladly explain what's going on there), or contribute this myself.

**Comment by lewisjkl** [comment]
Going to take a look at this issue later today or tomorrow. Will keep you posted if I run into any issues, but so far your work over in https://github.com/kubukoz/caliban-gitlab seems easy enough to follow 💯
