### ISSUE TITLE
When will publish new version?

### ISSUE THREAD

**Issue by pandaforme** [cb372/scalacache#416]
Is it possible to push the latest version of scalacache to Maven?
It seems not to bump a new version for a while.

**Comment by kubukoz** [comment]
hey, didn't see this before but there's a 1.0.0-M1 version with cats-effect in the core now. https://github.com/cb372/scalacache/releases/tag/v1.0.0-M1

**Comment by lewisjkl** [comment]
Also worth mentioning that I am going to publish a new milestone for scalacache soon after updating to the latest cats-effect milestone (see #450)

**Comment by kubukoz** [comment]
1.0.0-M3 and M4 have been published. If there are open PRs you'd like to see in a release, let me know :)
