### ISSUE TITLE
Cache trait should include effect type parameter.

### ISSUE THREAD

**Issue by PawelJ-PL** [cb372/scalacache#417]
Hi,

Currently Cache (and CacheAlg) trait contains only value type parameter (`V`) and effect type is provided for every single method.

I think, it should looks like:

```
trait CacheAlg[F[_], V]
```

and
```
trait Cache[F[_], V] extends CacheAlg[F, V]
```

so that is would be easy to create test implementation based on cats `Ref`, like:

```scala
def instance[F[_]: Sync, A]: F[Cache[F, A]] =
    Ref.of[F, Map[Seq[Any], A]](Map.empty).map { cache =>
      new Cache[F, A] {
        override def config: CacheConfig = ???

        override def cachingForMemoize(baseKey: String)(ttl: Option[Duration])(f: => A)(implicit mode: Mode[F], flags: Flags): F[A] = ???

        override def cachingForMemoizeF(baseKey: String)(ttl: Option[Duration])(f: => F[A])(implicit mode: Mode[F], flags: Flags): F[A] = ???

        override def get(keyParts: Any*)(implicit mode: Mode[F], flags: Flags): F[Option[A]] = cache.get.map(values => values.get(keyParts))

        override def put(keyParts: Any*)(value: A, ttl: Option[Duration])(implicit mode: Mode[F], flags: Flags): F[Any] = cache.update(prev => prev + (keyParts -> value)).map(_ => true)

        override def remove(keyParts: Any*)(implicit mode: Mode[F]): F[Any] = ???

        override def removeAll()(implicit mode: Mode[F]): F[Any] = ???

        override def caching(keyParts: Any*)(ttl: Option[Duration])(f: => A)(implicit mode: Mode[F], flags: Flags): F[A] = ???

        override def cachingF(keyParts: Any*)(ttl: Option[Duration])(f: => F[A])(implicit mode: Mode[F], flags: Flags): F[A] = ???

        override def close()(implicit mode: Mode[F]): F[Any] = ???
      }
    }
```

**Comment by lewisjkl** [comment]
I agree that this would make more sense. Off the top of my head I can't think of an advantage to having it provided in each method rather than at the instance level. Did you want to take a crack at a PR for this?

**Comment by PawelJ-PL** [comment]
I'll try, but it will be breaking change (signatures will be changed)

**Comment by PawelJ-PL** [comment]
Sorry for the confusion, but I can see, that it has been changed in https://github.com/cb372/scalacache/commit/ac2133148519f2cc516406ed664962bb75577a02. So I'm closing the issue. Could you please release new version?

**Comment by cb372** [comment]
Yes, this change has already been made as part of the wider changes to introduce cats-effect.

We're not quite ready to release a new version yet, but there are snapshots available on Sonatype if you want to play around with what's on master: https://oss.sonatype.org/content/repositories/snapshots/com/github/cb372/scalacache-core_2.12/0.28.0+176-f172e869-SNAPSHOT/

**Comment by PawelJ-PL** [comment]
Ok thank you. So I'm closing the issue
