### ISSUE TITLE
Futures Are Always Created for Local Cache Accesses

### ISSUE THREAD

**Issue by mslinn** [cb372/scalacache#54]
Local cache accesses generally return a result very quickly, especially for low concurrency values for Guava. Creating and invoking an ExecutionContext requires a context switch, which has non-trivial overhead. I do not believe that wrapping a computation in a Future provides any benefit in this case. 

Instead of calling Await.result() for every synchronous request, the opposite approach would handle all use cases better: synchronous requests should be performed without a Future, and asynch results should wrap synchronous calls in a Future.

**Comment by cb372** [comment]
This is an artifact of ScalaCache being a facade across a number of different cache implementations, some non-blocking (Guava, Ehcache depending on configuration) and some blocking (Ehcache depending on configuration, Redis, Memcache). If we were to split it into separate APIs for each case, it would no longer be a facade, as you would need to rewrite your client code if you wanted to switch your cache implementation from e.g. Guava to Redis.

In fact, the Guava implementation wraps its results in `Future.succesful()`, which is different from wrapping it in `Future { ... } `. It creates a special kind of `Future` called a `KeptPromise`, so calling `Await.result` should not result in any context switching or other overhead.
