### ISSUE TITLE
Support async access in memoize

### ISSUE THREAD

**Issue by YunLiaw** [cb372/scalacache#59]
Currently the memoize can only be applied to some function `f` that return the object that we want to cache, like the example in the demonstrated:

```
def getUser(id: Int): User = memoize {
  // Do DB lookup here...
  User(id, s"user${id}")
}
```
But the case is that most of the time we do the DB lookup in a async manner. 
That is to say, we do the DB lookup in a async way, so the return type of the `getUser` function is usually `Future[User]`, rather than `User`. It will be great if this can be supported.

**Comment by cb372** [comment]
Was this closed accidentally? I think it's a valid issue, and it's something I have been meaning to address for a while.

I think we should change the signature to `def memoize[A](f: => Future[A])(implicit ...): Future[A]` (it's a breaking change but we're not at 1.0 yet). We can maybe also provide a convenience method `memoizeSync[A](f: => A)` that just wraps the result in a `Future.successful`.

In general I'd like to tidy up the API to consistently use Future across the board before 1.0.
