### ISSUE TITLE
Use tut to check README

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#61]
https://github.com/tpolecat/tut

**Comment by hamishdickson** [comment]
Hi, I have the beginnings of this here: https://github.com/hamishdickson/scalacache/commit/3f9f42d4a4fee99cc35ad62dd7b6683cf3a50e43

I might have to define quite a few dummy values to get this to compile - let me know if you'd rather I didn't do that or there is anything I should avoid trying to get to typecheck

**Comment by hamishdickson** [comment]
Oh, by the way, if you want to play with this yourself, just run `scalacache-docs/tut` in sbt and it will generate the README in the base directory for you

**Comment by cb372** [comment]
Awesome! Thanks for tackling this. Once everything is tut'd it'll be pretty
easy to turn it into a microsite as the next step.

I'm on holiday without a laptop this week but I'll take a look next week.

**Comment by hamishdickson** [comment]
No problem, hope you've had a good one! I've been on holiday as well, but will hopefully find time to finish this this week

**Comment by cb372** [comment]
Fixed as part of #145
