### ISSUE TITLE
GuavaCache invalid TTL (toExpiryTime => DateTime.now.plusMillis(ttl.toMillis.toInt))

### ISSUE THREAD

**Issue by pgorin** [cb372/scalacache#65]
ttl.toMillis.toInt is corrupted when using large numbers.
I think that can be fixed using DateTime.now.plus(ttl.toMillis).

**Comment by cb372** [comment]
Sorry about the slow reply, I just got back from holiday.

That's a good point, and your suggested fix sounds perfect. I'll make a PR soon. Thanks for reporting!

**Comment by pgorin** [comment]
Great! Thanks you!
