### ISSUE TITLE
Fix up build.sbt

### ISSUE THREAD

**Issue by mdedetrich** [cb372/scalacache#67]
I just did a clone of scalacache, and I am getting this error when running sbt at this point

```sbt
lazy val deployToMavenCentral = ReleaseStep(action = releaseTask(sonatypeReleaseAll))
```

Seems like its relying on a non committed file for release reasons?

**Comment by cb372** [comment]
Sorry about the slow reply, I just got back from holiday.

Did you manage to solve this issue? I'm afraid I can't reproduce it. 

ScalaCache uses the sbt-sonatype plugin to push releases to the Sonatype OSS repository. But the plugin is [listed in plugins.sbt](https://github.com/cb372/scalacache/blob/master/project/plugins.sbt#L3), so sbt should run fine. The plugin depends on a file `~/.sbt/0.13/sonatype.sbt`, where I configure my Sonatype credentials, but I tried removing that file and sbt still ran fine.

Could you give me some more info about what kind of error you are getting?

**Comment by mdedetrich** [comment]
Actually I think I may know what the issue is, I am using SonaType plugin as well for my own projects, and I think there may be a version mismatch

I am using

``sbt
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "0.5.0")
```

What version of sonatype do you use?

**Comment by cb372** [comment]
OK, I'll update my `sbt-sonatype` to the latest version. I didn't realise it was so out of date.
