### ISSUE TITLE
Start looking at/building for Scala 2.12?

### ISSUE THREAD

**Issue by mdedetrich** [cb372/scalacache#76]
Scala 2.12 is already in M3, and a lot of major libraries are cross building/doing releases against it. Would be good if Scala Cache did the same, as it would iron out any potential compatibility release before Scala 2.12 hits an actual release

**Comment by cb372** [comment]
Yep, this is definitely on my TODO list. Fingers crossed that the macros don't break!

**Comment by cb372** [comment]
M4 will be out any day now. I'd like to take care of this soon.

Will require a bit of sbt tweaking, because some of the integration tests (Play, Squeryl) will need to be excluded. The sbt-release plugin will also need to be fixed to work with cross-building.

**Comment by cb372** [comment]
Finally got around to this! Just merged in #101
