### ISSUE TITLE
How to upgrade CatsEffect modes?

### ISSUE THREAD

**Issue by struong** [cb372/scalacache#789]
Hi 

I am using `implicit val mode: Mode[F] = scalacache.CatsEffect.modes.async`

I am upgrading from `0.28.0` to `1.0.0-M6` and noticed that `scalacache-cats-effect` is stuck on `0.28.0`, I can't find anywhere in the docs on what this mode should be now. Can anyone help please?

Thanks!

**Comment by kubukoz** [comment]
Hey, FYI this library isn't actively maintained. However, if you're happy to upgrade to 1.0.0-M6, Cats Effect is now baked into the core module so you don't need any extra modules.

**Comment by struong** [comment]
Oh nevermind @kubukoz I can see that you can literally just specify the effect type in your `Cache` now, thanks!

```
trait Cache[F[_], K, V]
```
