### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by cb372** [cb372/scalacache#82]
Would be interesting to see how much overhead ScalaCache adds vs using a cache implementation directly.

JMH?

**Comment by wuservices** [comment]
I just started using scalacache with memoize and it seemed like there was some very significant overhead, so I did some informal tests. I found that when I use memoize, things are quite a bit slower. get/put performance was decent and I actually didn't notice that there was some overhead until I did tons of gets.

Am I doing this correctly? It seems like I get 30x overhead with get/put and scalacache but almost 1500x overhead when using memoize.

See https://gist.github.com/wuservices/4568ab3959e5234a9b10e1b1e2cbd0ab

```
Run #3 (1000000 iterations per run)
Uncached / return directly in 5.9 ms
scalacache get no memoize in 369.4 ms
scalacache get with memoize in 15857.4 ms
get from Caffeine directly in 9.9 ms
get from underlying ConcurrentHashMap in 11.0 ms
get using scaffeine in 14.6 ms
```

**Comment by cb372** [comment]
First of all, big thanks for providing those benchmarks. This is something I should have done ages ago.

I've [started porting your benchmark code](https://github.com/cb372/scalacache/commit/b12150d94d503a7e5cc85cc32ccd706a9574e433) over to JMH, which I find to be the most reliable benchmarking framework. So far, I get similarly distressing results! I'll need to do some profiling and bytecode inspection to work out what is causing the slowdown, but I have a few ideas for things that can be optimised.

Until now I haven't really focussed on performance optimisation for ScalaCache, because its main use case is for caching either HTTP requests or DB calls, both of which are a zillion times slower than hitting the cache. But I didn't realise the overhead was this significant.

**Comment by wuservices** [comment]
Thanks for checking that out. Definitely understand where you're coming from and it's only by chance I decided to look into this. I have some code that grabs stuff from cache for hundreds of thousands of items so I was timing that vs database lookups. For now I'm going to start with scaffeine and will probably just use a loading cache in place of memoize and have the benefit of some stats on load times too. 

Longer run I was definitely interested in using Redis with scalacache at some point and keeping a similar API to my local cache. Even with using scaffeine, switching back and forth between it and scalacache is trivial.

**Comment by ben-manes** [comment]
I'd first tune your JVM settings. GC can have a high impact on micro-benchmarks, but not be a problem in regular usage. The default GC is the throughput collector, whereas you probably want a concurrent collector for these cases. Creating garbage will still have a penalty, but be a fair measurement. Both Caffeine and ConcurrentHashMap avoid creating garbage on reads, whereas I believe ScalaCache is less fortunate due to its key generator.

I use `-server -Xmx2G -XX:+UseG1GC -XX:-UseBiasedLocking` in my benchmarks.

**Comment by cb372** [comment]
@ben-manes Thanks for the tip. Unfortunately it didn't make a big difference to the numbers. But I think you're right that the garbage caused by the key generation is probably the biggest cause of slowdown.

I'd never heard of biased locking before. You learn something new every day!

**Comment by cb372** [comment]
By the way, here are the results on my (sluggish) MacBook Air, running with the JVM args suggested above. JMH settings: `-wi 10 -i 10 -f 3`.

```
[info] Benchmark                                      Mode  Cnt      Score      Error  Units
[info] CaffeineBenchmark.caffeineGet                  avgt   30     20.547 ±    0.596  ns/op
[info] CaffeineBenchmark.scalacacheGetNoMemoize       avgt   30    334.866 ±   32.630  ns/op
[info] CaffeineBenchmark.scalacacheGetTypedNoMemoize  avgt   30    340.825 ±   36.284  ns/op
[info] CaffeineBenchmark.scalacacheGetWithMemoize     avgt   30  39801.345 ± 2974.877  ns/op
```

**Comment by cb372** [comment]
Closing this issue, as we now have benchmarks.

**Comment by mdedetrich** [comment]
@cb372  Although this is already closed, you may want to you have a look at https://scalameter.github.io/. I use it for all of my benchmarking, and its actually able to account for GC pressure (and comes with a very handy Generator library as well). You can also specify for tests to be run in process, or seperate JVM forks to try and get a proper control over how GC works
