### ISSUE TITLE
Call to `cachingWithTTL` (via macro `memoizeSync`) never returns...

### ISSUE THREAD

**Issue by JustAHappyKid** [cb372/scalacache#83]
Apologies if I'm doing something wrong, but I can't imagine what. It appears as though the (`private`) `_cachingSync` method is awaiting (via `Await.result`) a `Future` that either doesn't exist or was attached to a thread that has somehow disappeared or died off.

I first notice this problem when my `main` thread locks up -- I see no further log messages from my application. I've allowed it to stay in this state for up to (give or take) 24 hours. A `jstack` dump (see attached) appears to show the `main` thread locked up, waiting for the cache to come back, but there doesn't appear to be any other thread busy "looking" for the respective value (to be cached).

The method that uses the cache looks like this, where `Session` refers to a Slick database session/connection:

      def find(mid: String)(implicit s: Session): Option[Merchant] =
        memoizeSync(10.minutes) {
          // Query the database here...
        }

(In the attached `jstack` dump, I've simply clipped the irrelevant portion of the `main` thread's stack-trace.)

I am using the Guava back-end and my `ScalaCache` object is initialized as such:

    implicit val scalaCache = scalacache.ScalaCache(scalacache.guava.GuavaCache())

[jstack.txt](https://github.com/cb372/scalacache/files/93045/jstack.txt)

**Comment by cb372** [comment]
Sorry, I totally missed this! Have you discovered any more clues since you filed the issue? I'll start investigating this.

**Comment by cb372** [comment]
Hmm, this is really weird. How often does this problem occur? Just occasionally? I've tried repeatedly calling memoizeSync with Guava but I can't reproduce it.

Are you using the latest version (0.7.5) of ScalaCache?

Sorry I can't be of more help. I'll keep thinking about what could cause this.

**Comment by JustAHappyKid** [comment]
Hi -- thanks for following up. :-)  Actually, I'm not sure I've seen this problem again since I posted. It was quite bizarre, and I know it occurred more than once. I am using version 0.7.5 now, though not certain I was on that version when the problem occurred (but was running a 0.7.x version, IIRC).

At this point feel free to close this ticket... If I experience the problem again I'll try to follow up, hopefully with more detail. Thanks!
