### ISSUE TITLE
if i want the true result from get(key), should i use Await? (guava cache)

### ISSUE THREAD

**Issue by jeffbondlink** [cb372/scalacache#84]
I'm having a bit of a hard time converting the result of the future cache get to an object that the calling method can read and use.  In this case its a Map.

I can use Await.result(futureVal, Duration(1,"seconds") which works wonderfully, while this is more of a future question about getting the direct result from a future into a variable, i'm wondering what the canonical way to do this is with ScalaCache.  Await, to me seems better than the sync calls (which...have they been removed, don't see them in the code, but they are in the readme?), since i can recover and repopulate if empty.

BTW, i think the wrapper library for all these caches is really nice.  

Thanks for your contribution.

**Comment by cb372** [comment]
The sync calls are still there, but the API was moved around a bit between 0.6.x and 0.7.x. Apologies if the README is unclear or incorrect - documentation PRs welcome! Did you see the [synchronous API section](https://github.com/cb372/scalacache#synchronous-api)?

I would say the canonical way to do synchronous calls would be to use the synchronous API, e.g.

```scala
scala> import scalacache._
import scalacache._

scala> implicit val sc = ScalaCache(scalacache.guava.GuavaCache())
sc: scalacache.ScalaCache = ScalaCache(...)

scala> put("foo")("bar")
res0: scala.concurrent.Future[Unit] = scala.concurrent.impl.Promise$KeptPromise@287e5733

scala> sync.get[String]("foo")
res1: Option[String] = Some(bar)
```

Actually all that `sync.get` is doing is exactly what you suggested, using `Await.result`. You can see the code [here](https://github.com/cb372/scalacache/blob/3f0145ab1793c4055b6c773f7a4ae1aa816d2757/core/src/main/scala/scalacache/package.scala#L103-L104). 

The only difference is that by calling `Await.result` yourself you have control over the timeout. The sync API will wait forever, which can be very dangerous. e.g. if you're using Redis or Memcache and you lose your connection for whatever reason, the thread might block forever and cause your app to hang.

Hope this answers your question.
